# numpy处理数据

## Prerequisites

In [ ]:
import numpy as np

## 生成序列

使用numpy生成等差数列有两种方式：

方式一：使用`np.arange(start, stop, step)`，这种方式便于生成元素之差为step的数组

方式二：使用`np.linspace(start, stop, num)`，这种方式便于生成元素个数为num的数组，还可以通过endpoint参数指定元素是否包含端点。

In [61]:
A = np.arange(0, 3, 0.1)  # 数据的间距为0.1
B = np.linspace(0, 3, 30, endpoint=True) # 生成30个元素，包含端点0和3，默认包含

print(f'The endpoints of A:{A[0]},{A[-1]}')
print(f'The endpoints of B:{B[0]},{B[-1]}')


The endpoints of A:0.0,2.9000000000000004
The endpoints of B:0.0,3.0


## numpy数组

**`np.ndarray`类和`np.array`函数**

由`np.array`生成的数组是np.ndarray类的实例，可以用`isinstance(a, np.ndarray)`进行验证。

数组的生成有很多种方式，例如`array、linspace、arange、full、eye、emptys、ones、zeros`，比较常用的是前五个：`array、linspace、arange、full、eye`，其中full可以使数组填充给定值，eye生成单位矩阵。

empty和ones的区别：empty和ones都生成指定shape的数组，但是empty不进行初始化，ones将数组初始化为0。

例子如下：


In [58]:
# numpy数组

A = np.array([1,2,3,3,4])
B = np.linspace(1, 12, 9)
C = np.arange(1, 12, 2)

# full填充
D = np.full((3,4), 9)
# 生成五行数组，每行数组都是[5,3,4]
E = np.full((5,3), [5,3,4])
print(f'E:\n{E}')

# 单位矩阵
F = np.eye(4)

# ones、zeros可以用full来代替

E:
[[5 3 4]
 [5 3 4]
 [5 3 4]
 [5 3 4]
 [5 3 4]]


In [46]:
import numpy as np
a = np.reshape(np.arange(1,13),(3,4))
b = np.reshape(np.arange(2,14),(4,3))
print(id(a))
print(id(a*2))
isinstance(a, np.ndarray)
isinstance(np.array_repr, np.ndarray)

2239416229200
2239381295824


False

## 矩阵乘法
矩阵乘法可以有四种操作，数乘、点乘、元素积(elementwise)、Kronecker积，但当前阶段只需要用到前三种，第四种先不管。

数乘即将一个数与矩阵中的各个数相乘，numpy中使用`*`来完成数乘（`*`运算也用来进行元素积）：
\begin{align*}
A*2=
\begin{pmatrix}
 1 &  2 &  3 &  4 \\
 5 &  6 &  7 &  8 \\
 9 & 10 & 11 & 12
\end{pmatrix}
*2 = 
\begin{pmatrix}
 1*2 &  2*2 &  3*2 &  4*2 \\
 5*2 &  6*2 &  7*2 &  8*2 \\
 9*2 & 10*2 & 11*2 & 12*2
\end{pmatrix}
\end{align*}
注意A*2的行列式计算:$|A*2| = 2^3|A|$


矩阵点乘即线性代数中所介绍的矩阵乘法，AB要求A的列数等于B的行数，在numpy中使用`np.dot(A,B)`来完成矩阵乘法，或者使用`@`运算符，`A @ B`

矩阵元素积(elementwise)是指将两个矩阵中相同位置的元素对应相乘，这要求连个矩阵的shape相同，在numpy中用`*`来完成矩阵乘法，`*`运算也用来完成数乘

注意，`*`运算会产生一个新的数组（数乘和元素积都会产生新数组），可以用id()函数进行检验。

如果不想产生新数组，可以使用运算符`*=、+=`等运算符。

In [44]:
import numpy as np
A = np.reshape(np.arange(1,7), (2, 3))
B = np.reshape(np.arange(2,8), (3, 2))
print('矩阵A和B')
print(f'A:{A}\nB:{B}')
# 数乘
C = A*2
print('*运算符生成新数组，导致A和A*2的id不同')
print(f'id of A:{id(A)}\nid of A*2:{id(C)}')

# 点积，即矩阵乘法
D = A@B  # 或者np.dot(A, B)
print('用@进行点积运算')
print(f'D:{D}')

# 元素积，elementwise，矩阵的shape需要一致
E = A*A
print('用*进行元素积（elementwise）')
print(f'A*A：{E}')

矩阵A和B
A:[[1 2 3]
 [4 5 6]]
B:[[2 3]
 [4 5]
 [6 7]]
*运算符生成新数组，导致A和A*2的id不同
id of A:2239416229392
id of A*2:2239416294448
用@进行点积运算
D:[[28 34]
 [64 79]]
用*进行elementwise
A*A：[[ 1  4  9]
 [16 25 36]]


## 维度操作（轴操作）

In [2]:
help(np.ndarray)
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array